# Welcome to Bridgetown!
#
# This config file is for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
#
# A list of all available configuration options can be found here:
# https://www.bridgetownrb.com/docs/configuration/options
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bin/bridgetown start`. If you change this file, please restart the server process.
#
# For reloadable site metadata like title, SEO description, social media
# handles, etc., take a look at `src/_data/site_metadata.yml`
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

url: "https://www.eightbitraptor.com"

permalink: ":year/:month/:day/:slug/"
template_engine: erb

# Other options you might want to investigate:
#
# base_path: "/" # the subpath of your site, e.g. /blog. If you set this option,
# ensure you use the `relative_url` helper for all links and assets in your HTML.
# If you're using esbuild for frontend assets, edit `esbuild.config.js` to
# update `publicPath`.

timezone: Europe/London
pagination:
  enabled: true

collections:
  weeknotes:
    output: true
    permalink: "weeknotes/:slug/:title/"
    sort_by: slug
    sort_direction: descending
  talks:
    output: true
    permalink: "talks/:slug/"
    sort_by: date
    sort_direction: descending

feed:
  excerpt_only: true
  collections:
    weeknotes:
      path: "/weeknotes.xml"
